version: '3.8'

services:
  mock-backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    restart: unless-stopped
